import { Todo } from "./Todo";

export type TaskBoxProps = {
  modal2:string;
  setModal2: Function;
  show2: boolean;
  setShow2: Function;
  preTodos: Todo[];
  setPreTodos: Function;
  eight: Todo[];
  setEight: Function;
  nine: Todo[];
  setNine: Function;
  ten: Todo[];
  setTen: Function;
  eleven: Todo[];
  setEleven: Function;
  twelve: Todo[];
  setTwelve: Function;
  thirteen: Todo[];
  setThirteen: Function;
  fourteen: Todo[];
  setFourteen: Function;
  fifteen: Todo[];
  setFifteen: Function;
  sixteen: Todo[];
  setSixteen: Function;
  seventeen: Todo[];
  setSeventeen: Function;
};